// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoscrollController from "./autoscroll_controller"
application.register("autoscroll", AutoscrollController)

import DatepickerController from "./datepicker_controller"
application.register("datepicker", DatepickerController)

import SpoilerController from "./spoiler_controller"
application.register("spoiler", SpoilerController)

import ThemeSelectController from "./theme_select_controller"
application.register("theme-select", ThemeSelectController)
