// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnchorBlankerController from "./anchor_blanker_controller"
application.register("anchor-blanker", AnchorBlankerController)

import AutofocusController from "./autofocus_controller"
application.register("autofocus", AutofocusController)

import AutoscrollController from "./autoscroll_controller"
application.register("autoscroll", AutoscrollController)

import ColouradjustController from "./colouradjust_controller"
application.register("colouradjust", ColouradjustController)

import ContrastsliderController from "./contrastslider_controller"
application.register("contrastslider", ContrastsliderController)

import CssinjectController from "./cssinject_controller"
application.register("cssinject", CssinjectController)

import DatepickerController from "./datepicker_controller"
application.register("datepicker", DatepickerController)

import PresenceController from "./presence_controller"
application.register("presence", PresenceController)

import SpoilerController from "./spoiler_controller"
application.register("spoiler", SpoilerController)

import ThemeSelectController from "./theme_select_controller"
application.register("theme-select", ThemeSelectController)

import TypingController from "./typing_controller"
application.register("typing", TypingController)

import WysiwygController from "./wysiwyg_controller"
application.register("wysiwyg", WysiwygController)
